#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  rightDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftDriveEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  pClaw,          sensorDigitalOut)
#pragma config(Sensor, I2C_1,  rightLiftEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           driveOuterRight, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           driveInnerRight, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           driveOuterLeft, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           driveInnerLeft, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftOuterRight, tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port7,           liftInnerRight, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           liftOuterLeft, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           liftInnerLeft, tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        												Drive PID																	 */
/*                                                                           */
/*---------------------------------------------------------------------------*/

#define wheelDiameter  	 	4.0    // Inches.
#define ticksPerRev    	 	360.0  // Quadrature Encoder.
#define driveDiameter    	11.5   // Inches.

#define inchesToTicks(x) 	((x) * (ticksPerRev / (PI * wheelDiameter)))
#define degreesToTicks(x)	inchesToTicks((x) * ((driveDiameter / 2.0) * (PI / 180.0)))

short trueSpeed(short speed) {
	if (speed == 0) {
		return 0;
	}
	short x = abs(speed);

	if (x > 127) {
		x = 127;
	}
	return sgn(speed) * ((((0.000001115136722 * x - 0.0001834554708) * x
			+ 0.01010261354) * x + 0.01924469053) * x + 11.46841392);
}

void drive(int maxPower, int encoderTicks, int turnValue) {
	const float Kp = 0.95;
	const float Kd = 10.0;
	const float correctionKp = 2.0;
	const int thresholdTicks = 15;
	const long durationMs = 250;

	int lastError;
	int lastTime = nSysTime;
	int lastTimeOutside = nSysTime;  // Stores last nSysTime where abs(error) was > thresholdTicks.
	int rightEncoder, leftEncoder, dt, error, correctionPower, rightPower, leftPower;
	float derivative;

	// Save encoder values.
	int initialEncoderR = SensorValue[dgtl1];
	int initialEncoderL = SensorValue[dgtl3];

	while (true) {
		rightEncoder = SensorValue[dgtl1] - initialEncoderR;
		leftEncoder = turnValue * (SensorValue[dgtl3] - initialEncoderL);
		dt = nSysTime - lastTime;

		error = encoderTicks - (sgn(maxPower) * (rightEncoder + leftEncoder) / 2);
		derivative = (dt == 0) ? 0.0 : (float)(error - lastError) / dt;

		correctionPower = correctionKp * (rightEncoder - leftEncoder);
		rightPower = Kp * error + Kd * derivative - correctionPower;
		if (abs(rightPower) > abs(maxPower)) {
			rightPower = sgn(rightPower) * abs(maxPower);
		}
		// Normalize left and right power to ensure full use of correctionPower.
		leftPower = turnValue * (rightPower + 2 * correctionPower);
		if (abs(leftPower) > abs(maxPower)) {
			leftPower = sgn(leftPower) * abs(maxPower);
		}
		rightPower = turnValue * leftPower - 2 * correctionPower;
		if (abs(rightPower) > abs(maxPower)) {
			rightPower = sgn(rightPower) * abs(maxPower);
		}
		motor[driveOuterRight] = motor[driveInnerRight] = rightPower;
		motor[driveOuterLeft] = motor[driveInnerLeft] = leftPower;

		// Handle exiting when error is small enough for long enough.
		if (abs(error) < thresholdTicks) {
			if (nSysTime - lastTimeOutside > durationMs) {
				break;  // Stop driving and exit.
			}
		} else {
			lastTimeOutside = nSysTime;
		}
		lastTime += dt;
		lastError = error;

		sleep(15);
	}
	motor[driveOuterRight] = motor[driveInnerRight] = motor[driveOuterLeft] = motor[driveInnerLeft] = 0;
}

void driveForward(int power, float inches) {
	drive(abs(power), inchesToTicks(abs(inches)), 1);
}

void driveBackward(int power, float inches) {
	drive(abs(power), inchesToTicks(-abs(inches)), 1);
}

void turnRight(int power, float degrees) {
	drive(abs(power), degreesToTicks(-abs(degrees)), -1);
}

void turnLeft(int power, float degrees) {
	drive(abs(power), degreesToTicks(abs(degrees)), -1);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        												Lift PID																	 */
/*                                                                           */
/*---------------------------------------------------------------------------*/

int liftTarget;
int liftTargetPosition = 0;
int liftHoldPower;
int liftCurrentPosition = 0; // used for debugging
int liftMotorPower = 0;

task liftUserControl()
{
	nMotorEncoder[liftOuterRight] = 0;
	liftTargetPosition = nMotorEncoder[liftOuterRight];
	while(true)
	{
					if(vexRT[Btn6U] == 1) //if lift up button is pressed the do the following
					{
						if (liftTargetPosition != -10000) {
							liftTargetPosition = -10000; //ensure that lift target won't be set until after either 6U or 6D is released
							liftMotorPower = -127; //set lift power
						}
						motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = liftMotorPower;

					}

				else if(vexRT[Btn6D] == 1) //if lift down button is pressed the do the following
				{
					if (liftTargetPosition != -10000) {
						liftTargetPosition = -10000; //ensure that lift target won't be set until after either 6U or 6D is released
						liftMotorPower = 127;
					}
					motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = liftMotorPower;

				}

				else
				{
					if(liftTargetPosition == -10000)
						{
							liftTargetPosition = nMotorEncoder[liftOuterRight]; //set lifttarget to encoder value

								if(liftMotorPower >= 0)
							{
								motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = 0;
							}
							else {
								while(liftMotorPower < -80)
								{
									wait1Msec(10);
									motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = liftMotorPower; //bring motor power to a gradual stop
									liftMotorPower += 10;

								}
							}
						}
				{
					if(abs(liftTargetPosition - nMotorEncoder[liftOuterRight]) > 35 && nMotorEncoder[liftOuterRight] > 50) //set a tolerance to romove uncessecary oscillation
						{
							liftHoldPower = (liftTargetPosition - nMotorEncoder[liftOuterRight]) / 2; //find the error and scale

							motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerRight] = motor[liftInnerLeft] = -liftHoldPower; //correct for error

							wait1Msec(20);
						}
						else
							{
							if(liftTargetPosition > 65 && nMotorEncoder[liftOuterRight] > 50)
								{
									motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = -22; //if error is inside of tolerance set motor power to 22
								}
								else {
									motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = 2; //if lift is down set a hold power and reset encoder to maintain acceracy
									nMotorEncoder[liftOuterRight] = 0;
								}
							}
				}
			}
				wait1Msec(20);
		}
}



task liftAuton()
	{
		while(true) {

					if(liftTarget > 0 && nMotorEncoder[liftOuterRight] < liftTarget) //if lift up button is pressed the do the following
					{
						if (liftTargetPosition != -10000) {
							liftTargetPosition = -10000; //ensure that lift target won't be set until after action is completed
							liftMotorPower = -127; //set lift power
						}
						motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = -127;

					}

				else if(liftTarget == 0 && nMotorEncoder[liftOuterRight] > liftTarget) //if lift down button is pressed the do the following
				{
					if (liftTargetPosition != -10000) {
						liftTargetPosition = -10000; //ensure that lift target won't be set until action is completed
						liftMotorPower = 127;
					}
					if(nMotorEncoder[liftOuterRight] > 50)
						{
							motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = 127;
						}
						else {
							motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = 0;
						}
				}

				else
				{
					if(liftTargetPosition == -10000)
						{
							liftTargetPosition = nMotorEncoder[liftOuterRight]; //set lifttarget to encoder value

								if(liftMotorPower >= 0)
							{
								motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = 0;
							}
							else {
								while(liftMotorPower < -80)
								{
									wait1Msec(10);
									motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = liftMotorPower; //bring motor power to a gradual stop
									liftMotorPower += 10;

								}
							}
						}
				{
					if(abs(liftTargetPosition - nMotorEncoder[liftOuterRight]) > 35 && nMotorEncoder[liftOuterRight] > 50) //set a tolerance to romove uncessecary oscillation
						{
							liftHoldPower = (liftTargetPosition - nMotorEncoder[liftOuterRight]) / 2; //find the error and scale

							motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerRight] = motor[liftInnerLeft] = -liftHoldPower; //correct for error

							wait1Msec(20);
						}
						else
							{
							if(liftTargetPosition > 65 && nMotorEncoder[liftOuterRight] > 50)
								{
									motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = -22; //if error is inside of tolerance set motor power to 22
								}
								else {
									motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = 2; //if lift is down set a hold power and reset encoder to maintain acceracy
									nMotorEncoder[liftOuterRight] = 0;
								}
							}
				}
			}
				wait1Msec(20);
			}
		}

	////Autonomous mode////

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	SensorValue[pClaw] = 0;
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


////AUTONOMOUS////

task autonomous()
{
	stopTask(liftUserControl);
	startTask(liftAuton);


	SensorValue[rightDriveEncoder] = SensorValue[leftDriveEncoder] = 0;
	driveForward(40, 10);

}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	stoptask(liftAuton);
	startTask(liftUserControl);


	while(true) {
	//	int jDifference = vexRT[Ch2] - vexRT[Ch3];

		//Drive
	/*	if((jDifference) <= 50 && jDifference >= 7 && ((vexRT[Ch2] >= 7 && vexRT[Ch3] >= 7) || (vexRT[Ch2] >= -7 && vexRT[Ch3] >= -7)))
		{
			motor[driveInnerLeft] = vexRT[Ch2];
			motor[driveOuterLeft] = vexRT[Ch2];

			motor[driveInnerRight] = motor[driveOuterLeft];
			motor[driveOuterRight] = motor[driveInnerLeft];
		}

*/
				motor[driveInnerLeft] = vexRT[Ch3];
				motor[driveOuterLeft] = vexRT[Ch3];

	      motor[driveInnerRight] = vexRT[Ch2];
				motor[driveOuterRight] = vexRT[Ch2];

		//Manual Encoder Reset

		if(vexRT[Btn7D] == 1)
		{
		 nMotorEncoder[liftOuterRight] = 0;
		}

		//Claw

		if(vexRT[Btn5U] == 1)
			{
      	SensorValue[pClaw] = 0;
    	}

		else if(vexRT[Btn5D] == 1)
			{
 				SensorValue[pClaw] = 1;
			}
	}
}
