#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  pClaw,          sensorDigitalOut)
#pragma config(Sensor, dgtl6,  ,               sensorTouch)
#pragma config(Sensor, I2C_1,  rightLiftEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           driveOuterRight, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           driveInnerRight, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           driveOuterLeft, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           driveInnerLeft, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftOuterRight, tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port7,           liftInnerRight, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           liftOuterLeft, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           liftInnerLeft, tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


bool isAutonomous = false;
int liftTargetPosition = 0;
int liftHoldPower;
int liftCurrentPosition = 0; // used for debugging

task lift()
{
	nMotorEncoder[liftOuterRight] = 0;
	liftTargetPosition = nMotorEncoder[liftOuterRight];
	int liftMotorPower = 0;
	while(true)
	{
			if(vexRT[Btn6U] == 1) //if lift up button is pressed the do the following
		{
			if (liftTargetPosition != -10000) {
				liftTargetPosition = -10000; //ensure that lift target won't be set until after either 6U or 6D is released
				liftMotorPower = -127; //set lift power
			}
			motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = liftMotorPower;

		}

		else if(vexRT[Btn6D] == 1) //if lift down button is pressed the do the following
		{
			if (liftTargetPosition != -10000) {
				liftTargetPosition = -10000; //ensure that lift target won't be set until after either 6U or 6D is released
				liftMotorPower = 127;
			}
			motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = liftMotorPower;

		}

		else
		{
			if(liftTargetPosition == -10000)
				{
					liftTargetPosition = nMotorEncoder[liftOuterRight]; //set lifttarget to encoder value

						if(liftMotorPower >= 0)
					{
						motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = 0;
					}
					else {
						while(liftMotorPower < -80)
						{
							wait1Msec(10);
							motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = liftMotorPower; //bring motor power to a gradual stop
							liftMotorPower += 10;

						}
					}
				}

			if(abs(liftTargetPosition - nMotorEncoder[liftOuterRight]) > 35) //set a tolerance to romove uncessecary oscillation
				{
					liftHoldPower = (liftTargetPosition - nMotorEncoder[liftOuterRight]) / 2; //find the error and scale

					motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerRight] = motor[liftInnerLeft] = -liftHoldPower; //correct for error

					wait1Msec(20);
				}
				else
					{
					if(liftTargetPosition > 65)
						{
							motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = -22; //if error is inside of tolerance set motor power to 22
						}
						else {
							motor[liftInnerRight] = motor[liftOuterRight] = motor[liftOuterLeft] = motor[liftInnerLeft] = 2; //if lift is down set a hold power and reset encoder to maintain acceracy
							nMotorEncoder[liftOuterRight] = 0;
						}
					}
		}

		wait1Msec(20);
	}
}
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	SensorValue[pClaw] = 1;
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


////AUTONOMOUS////

task autonomous()
{
	isAutonomous = true;
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	isAutonomous = false;
	startTask(lift);

	while(true) {
	//	int jDifference = vexRT[Ch2] - vexRT[Ch3];

		//Drive
	/*	if((jDifference) <= 50 && jDifference >= 7 && ((vexRT[Ch2] >= 7 && vexRT[Ch3] >= 7) || (vexRT[Ch2] >= -7 && vexRT[Ch3] >= -7)))
		{
			motor[driveInnerLeft] = vexRT[Ch2];
			motor[driveOuterLeft] = vexRT[Ch2];

			motor[driveInnerRight] = motor[driveOuterLeft];
			motor[driveOuterRight] = motor[driveInnerLeft];
		}

*/
				motor[driveInnerLeft] = vexRT[Ch3];
				motor[driveOuterLeft] = vexRT[Ch3];

	      motor[driveInnerRight] = vexRT[Ch2];
				motor[driveOuterRight] = vexRT[Ch2];


		//Lift



		//Manual Encoder Reset

		if(vexRT[Btn7D] == 1)
		{
		 nMotorEncoder[liftOuterRight] = 0;
		}

		//Claw

		if(vexRT[Btn5U] == 1)
			{
      	SensorValue[pClaw] = 1;
    	}

		else if(vexRT[Btn5D] == 1)
			{
 				SensorValue[pClaw] = 0;
			}
	}
}
